### ISSUE TITLE
Application name and localization

### ISSUE THREAD

**Issue by mounirlamouri** [w3c-webmob/installable-webapps#15]
I guess some website / webapp have different name/title depending on the locale. I believe Firefox OS allows that. It would be great to have this issue raised in the document.

**Comment by ernesto-jimenez** [comment]
True, all the platforms allow for localisation on the names. I'll add a section about this.

**Comment by marcoscaceres** [comment]
Can't servers handle their own localization? Seems redundant to include this... it would be like including:

```
<title>The foo<title>
<title lang="fr">Le foo<title>
<title lang="es">El foo<title>
```

**Comment by ernesto-jimenez** [comment]
That was my first thought. However, what happens when I change the language settings from Spanish to English? Does my phone still show the "Reminders" app as "Recordatorios" because I installed it with my phone in Spanish? Does the system need to trigger a re-download of all the manifests to see if the apps have different names in the new language?

I'll expand the section with this info.

**Comment by marcoscaceres** [comment]
yeah, that's basically part of the problem. It would be good to find out how often people change lang phones... also, one could re-request the manifest, etc. 

I have a related spec: ["Proposal: navigator.languages API"](https://gist.github.com/marcoscaceres/3f72a0324df9aedcbec5)
